name: Build and Publish to GitHub Releases

on:
  push:
    branches:
      - main      # Publishes BETA on pushes to main
    tags:
      - 'v*'      # Publishes RELEASE on tagged pushes like v1.0, v2.0, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build project
        run: mvn clean package

      - name: Rename JAR for Release Type
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            mv target/aiotpa-1.0-SNAPSHOT.jar target/aiotpa-RELEASE-${{ github.ref_name }}.jar
          else
            mv target/aiotpa-1.0-SNAPSHOT.jar target/aiotpa-BETA.jar
          fi

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: ${{ github.ref_name }}
          files: target/*.jar
          draft: false
          prerelease: ${{ github.ref != 'refs/tags/v*' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}